version: "3"


services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=coffee
      - POSTGRES_PASSWORD=coffee
      - POSTGRES_DB=coffee
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432