version: "3"


services:
  api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
      - admin
    environment:
      - DJANGO_SETTINGS_MODULE=coffee.settings.api
      - COFFEE_DATABASE_HOST=db

  admin:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=coffee.settings.admin
      - COFFEE_DATABASE_HOST=db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=coffee
      - POSTGRES_PASSWORD=coffee
      - POSTGRES_DB=coffee
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
      - api