# Generated by Django 3.2.7 on 2021-09-12 14:42

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('P', 'Preparation'), ('R', 'Ready'), ('D', 'Delivered')], default='W', max_length=1, verbose_name='Status')),
                ('order_detail', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(blank=True, null=True, verbose_name='Order Details'), size=None, verbose_name='Order Detail')),
                ('price', models.FloatField(verbose_name='Price')),
                ('products', models.ManyToManyField(related_name='products', to='product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
