# Generated by Django 3.2.7 on 2021-09-12 17:10

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_detail',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(), size=None, verbose_name='Order Detail'),
        ),
    ]
