# Generated by Django 3.2.7 on 2021-09-08 20:26

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210908_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(related_name='products', to='product.Option', verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='option',
            name='choices',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=32, verbose_name='Choices'), size=None),
        ),
    ]
